Feature/organize asso
KIClubinfo/upont pull request #270
Opened 2017-09-16 17:20 UTC by Delcatel

Réorganisation des assos par catégorie "asso", "club" ou autre et rangement dans la liste des assos par catégorie et état inactif.

2017-09-17 09:27 UTC, LouisTrezzini requested changes

2017-09-17 09:27 UTC, LouisTrezzini commented on back/package-lock.json
> +{
EUH ?

2017-09-17 09:27 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.html
> +             ng-repeat="club in clubs" ng-if="club.active && club.category==='asso'">
espaces autour du `===`

2017-09-17 09:27 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.html
> +             ng-repeat="club in clubs" ng-if="club.active && club.category==='club'">
Idem

2017-09-17 09:27 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.html
> +             ng-repeat="club in clubs" ng-if="club.active && club.category!=='asso' && club.category!=='club'">
idem

2017-09-17 09:27 UTC, LouisTrezzini commented on front/app/js/controllers/users/students/index.html
> +<<<<<<< HEAD
EUUUH

2017-09-17 09:27 UTC, LouisTrezzini commented on front/app/js/controllers/users/students/index.html
> +        <a class="Navbar__link" up-state-active ui-sref="root.users.students.family({slug: $root.me.family})" ng-if="$root.me.family">Famille</a>
Supprimer

2017-09-17 09:27 UTC, LouisTrezzini commented on front/package-lock.json
> +{
Tu utilises yarn ?

2017-09-17 09:38 UTC, Delcatel commented on front/package-lock.json
> +{
Non, je sais pas c'est composer qui m'avait fait ça je crois, ça date d'il y a un mois.

2017-09-19 09:49 UTC, LouisTrezzini commented on front/package-lock.json
> +{
Perdu, c'est npm@5 qui génère ces fichiers. Du coup fallait éventuellement garder celui du front mais surtout supprimer celui du back :p

2017-09-22 23:36 UTC, Delcatel commented
Une fixture existe par catégorie de club, ça me semble ok de mon côté. Inspiration de la catégorisation des clubs : https://admissibles.enpc.org/plaquette-alpha-ponts.pdf

2017-09-24 18:29 UTC, LouisTrezzini submitted a review, later dismissed

2017-09-24 18:29 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.html
> +<section row wrap>
Code dupliqué...
C'est mieux de faire une liste `var $scope.clubTypes = [ {name: "Assos", slug: "asso"}, ...];` et de boucler dessus sur la vue

2017-09-24 22:54 UTC, Delcatel commented on front/app/js/controllers/users/assos/list.html
> +<section row wrap>
Je vais faire ça

2017-09-26 09:44 UTC, LouisTrezzini submitted a review, later dismissed

2017-09-26 09:44 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.js
> +        $scope.clubSlugs = $scope.clubTypes.map(function(dico) { return dico['slug']; });
:+1: la programmation fonctionnelle
dico -> dict

2017-09-26 09:44 UTC, LouisTrezzini commented on front/app/js/controllers/users/assos/list.html
> +        <h2 class="padded" ng-bind="clubType['name']"></h2>
Pourquoi ng-bind plutôt que `{{ clubType["name"] }}` dans le corps de la balise ?

2017-09-26 09:45 UTC, LouisTrezzini commented
Tu peux corriger si tu veux puis te merger

2017-09-26 10:43 UTC, merged