Added photo commands
KIClubinfo/upont pull request #291
Opened 2018-09-18 12:19 UTC by YVanlaer

Added : - PhotoRemoveCommand.php : permet de supprimer la photo d'un user (utile pour les faux de l'algorithme UpdatePhoto)
             - PhotoUpdateCommand : modification de la fonction isSimilar. Création d'un algorithme perso qui permet de donner une meilleure comparaison entre les noms. Il ne fonctionne plus en % mais en unité arbitraire.

2018-09-19 15:32 UTC, LouisTrezzini commented
Vraie review https://github.com/KIClubinfo/upont/compare/92393969305cf29f48404c81e9412866ebc2ba96...upload-photo

2018-09-19 15:43 UTC, LouisTrezzini requested changes

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoRemoveCommand.php
> +            ->setDescription('Import missing photos from Facebook for the given promo')
mauvaise description

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoRemoveCommand.php
> +        $user->getImage()->removeUpload();
On ne supprime jamais un fichier : `$user->setImage(null);` suffira

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoRemoveCommand.php
> +	$em->flush();
Problème d'indentation, configure mieux ton IDE pour utiliser 4 espaces

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +                    $score += 5*exp(-($k - $last_index)/2);
code pas linté

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +    private function compareStr(string $str1, string $str2)
je ne suis pas en mesure de comprendre une si longue fonction, surtout sans commentaires ni docstring

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        $score += $this->compareStr($lastName, $lastName_fb) * 3; //Parameter may be adapted
mets de le 3 devant si tu ne veux pas qu'on le loupe

2018-09-19 15:43 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        $firstName_fb = $this->cleanString(substr($member['name'], 0, strpos($member['name'], ' ')));
pas de `_` dans les noms de variables en php (camelCase)

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa requested changes

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +            ->addOption('similarity-threshold', 's', InputOption::VALUE_REQUIRED, 'Similarity threshold with Fb profiles above which photos are imported in non-preview and non-interactive mode (arbit
Si tu veux aller plus loin tu peux rajouter une option pour choisir la fonction de comparaison

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        $output->writeln('Importing facebook photos for users (> ' . $similarityThreshold . ' score similar) :');
`similarity score` en anglais non ?

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +            $longName = $tmp;
Tu pouvais aussi
```
private function compareStr(string $string1,string $string2) {
    return strlen($string1) < strlen($string2) ? $this->compareOrderedStr($string1, $string2) : $this->compareOrderedStr($string2, $string1);
}
```

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        $k = 0;
Super dur à comprendre en nommant tes variables avec des lettres de l'alphabet

2018-09-19 16:48 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        return $str;
Il y a beaucoup de brésiliens avec des a tildés. Autant enlever les majuscules aussi ?

2018-09-19 17:44 UTC, YVanlaer commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +                    $score += 5*exp(-($k - $last_index)/2);
Ca a l'air d'être un ensemble de règles assez vaste, c'est-à-dire ?

2018-09-19 17:50 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +                    $score += 5*exp(-($k - $last_index)/2);
Ton IDE est capable de linter tous les langages normalement
J'ai été choqué par l'absence d'espaces autours des opérateurs

2018-09-19 18:18 UTC, YVanlaer commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +            ->addOption('similarity-threshold', 's', InputOption::VALUE_REQUIRED, 'Similarity threshold with Fb profiles above which photos are imported in non-preview and non-interactive mode (arbit
moyen. similar_text est très utile dans certains cas, mais là c'est vraiment un cas de comparaison particulier. Ma fonction est une fonction beaucoup moins générale mais donne globalement des meilleurs résultats sur ce qu'on cherche

2018-09-19 18:23 UTC, YVanlaer commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        return $str;
Yep pour les tildes, je rajoute
En revanche: j'ai fait un strtolower avant de replace, aucune inquiétude pour les majuscules donc.

2018-09-21 19:38 UTC, PhilippeFerreiraDeSousa requested changes
On va t'épargner d'écrire un test de cleanString ^^

2018-09-21 19:38 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +            if ($k < strlen($longName)) {
$k est pas défini, tu l'as renommé $currentIndex

2018-09-21 19:38 UTC, PhilippeFerreiraDeSousa commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +                $lastIndex = $k;
Same

2018-09-21 20:35 UTC, LouisTrezzini requested changes

2018-09-21 20:35 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoRemoveCommand.php
> +        $user->setImage($image);
setImage(null) et supprime la ligne précédente

2018-09-21 20:35 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        $shortName = $str1;
Remplacer tout ce bloc par 
If (s1 plus grand s2) {
Long, court = s1, s2
} Sinon {
 Long, court = s2, s1
}

Encore mieux d'extraire une méthode

2018-09-21 20:35 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +                $score += exp($matchingRow/2);
Pas linté

2018-09-21 20:35 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +        for ($i = 0 ; $i < strlen($shortName) ; $i++) {
Règle de lint bizarre, pas d'espace avant les ; normalement (typographie US)

2018-09-21 20:35 UTC, LouisTrezzini commented on back/src/KI/UserBundle/Command/PhotoUpdateCommand.php
> +	$unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
On utilise [] pas array pour construire une tableau
La fonction entière n'est pas lintée

2018-09-26 18:00 UTC, merged